/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type FeeSchedule = {
  _id: string
  _type: 'feeSchedule'
  _createdAt: string
  _updatedAt: string
  _rev: string
  dealerName: string
  slug: Slug
  setupFeeUsd?: number
  annualAdminFeeUsd?: number
  storageModel: 'flat' | 'scaling'
  storageFlatFeeUsd?: number
  storageScalingPercent?: number
  typicalPurchaseSpreadPercent: number
  typicalLiquidationSpreadPercent: number
  minimumInvestmentUsd?: number
  mandatorySalesCall?: boolean
  sourceUrl?: string
  dataVerifiedAt: string
}

export type ExpertCredential = {
  _id: string
  _type: 'expertCredential'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  credentialCategory: 'degree' | 'license' | 'certification'
  recognizedBy?: string
  dateEarned?: string
  verificationUrl?: string
}

export type EditorialGuidelines = {
  _id: string
  _type: 'editorialGuidelines'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  lastReviewedAt: string
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  pillar: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'pillar'
  }
  author: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  reviewedBy?: ReviewedBy
  publishedAt: string
  updatedAt: string
  summary?: string
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        tone?: 'info' | 'warning' | 'danger'
        body?: string
        _type: 'callout'
        _key: string
      }
    | {
        question: string
        answer: string
        _type: 'faq'
        _key: string
      }
    | {
        rows?: Array<{
          _ref: string
          _type: 'reference'
          _weak?: boolean
          _key: string
          [internalGroqTypeReferenceTo]?: 'feeSchedule'
        }>
        _type: 'feeTable'
        _key: string
      }
    | {
        children?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        _type: 'llmsOnly'
        _key: string
      }
    | {
        children?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'normal'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'blockquote'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        _type: 'llmsIgnore'
        _key: string
      }
  >
  seo?: Seo
}

export type ReviewedBy = {
  _type: 'reviewedBy'
  reviewer: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'author'
  }
  reviewedAt: string
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  jobTitle?: string
  bio?: string
  portrait?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  credentials?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'expertCredential'
  }>
  socialProfiles?: Array<{
    platform:
      | 'linkedin'
      | 'twitter'
      | 'sec-iapd'
      | 'finra-brokercheck'
      | 'other'
    url: string
    _type: 'profile'
    _key: string
  }>
}

export type Pillar = {
  _id: string
  _type: 'pillar'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  summary?: string
  order: number
  seo?: Seo
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  noIndex?: boolean
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | FeeSchedule
  | ExpertCredential
  | EditorialGuidelines
  | Article
  | ReviewedBy
  | Author
  | Pillar
  | Seo
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/queries.ts
// Variable: articleBySlugQuery
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    publishedAt,    updatedAt,    "pillar": pillar->{ _id, title, "slug": slug.current, order },    "author": author->{   _id,  name,  "slug": slug.current,  jobTitle,  bio,  "portrait": portrait.asset->url,  "credentials": credentials[]->{ _id, name, credentialCategory, recognizedBy, dateEarned, verificationUrl },  "socialProfiles": socialProfiles[]{ platform, url } },    "reviewedBy": reviewedBy{      reviewedAt,      "reviewer": reviewer->{   _id,  name,  "slug": slug.current,  jobTitle,  bio,  "portrait": portrait.asset->url,  "credentials": credentials[]->{ _id, name, credentialCategory, recognizedBy, dateEarned, verificationUrl },  "socialProfiles": socialProfiles[]{ platform, url } }    },    body,    seo  }
export type ArticleBySlugQueryResult = {
  _id: string
  title: string
  slug: string
  summary: string | null
  publishedAt: string
  updatedAt: string
  pillar: {
    _id: string
    title: string
    slug: string
    order: number
  }
  author: {
    _id: string
    name: string
    slug: string
    jobTitle: string | null
    bio: string | null
    portrait: string | null
    credentials: Array<{
      _id: string
      name: string
      credentialCategory: 'certification' | 'degree' | 'license'
      recognizedBy: string | null
      dateEarned: string | null
      verificationUrl: string | null
    }> | null
    socialProfiles: Array<{
      platform:
        | 'finra-brokercheck'
        | 'linkedin'
        | 'other'
        | 'sec-iapd'
        | 'twitter'
      url: string
    }> | null
  }
  reviewedBy: {
    reviewedAt: string
    reviewer: {
      _id: string
      name: string
      slug: string
      jobTitle: string | null
      bio: string | null
      portrait: string | null
      credentials: Array<{
        _id: string
        name: string
        credentialCategory: 'certification' | 'degree' | 'license'
        recognizedBy: string | null
        dateEarned: string | null
        verificationUrl: string | null
      }> | null
      socialProfiles: Array<{
        platform:
          | 'finra-brokercheck'
          | 'linkedin'
          | 'other'
          | 'sec-iapd'
          | 'twitter'
        url: string
      }> | null
    }
  } | null
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'blockquote'
          | 'h1'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        tone?: 'danger' | 'info' | 'warning'
        body?: string
        _type: 'callout'
        _key: string
      }
    | {
        question: string
        answer: string
        _type: 'faq'
        _key: string
      }
    | {
        rows?: Array<{
          _ref: string
          _type: 'reference'
          _weak?: boolean
          _key: string
          [internalGroqTypeReferenceTo]?: 'feeSchedule'
        }>
        _type: 'feeTable'
        _key: string
      }
    | {
        children?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        _type: 'llmsIgnore'
        _key: string
      }
    | {
        children?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?:
            | 'blockquote'
            | 'h1'
            | 'h2'
            | 'h3'
            | 'h4'
            | 'h5'
            | 'h6'
            | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<{
            href?: string
            _type: 'link'
            _key: string
          }>
          level?: number
          _type: 'block'
          _key: string
        }>
        _type: 'llmsOnly'
        _key: string
      }
  >
  seo: Seo | null
} | null
// Variable: allArticleSlugsQuery
// Query: *[_type == "article" && defined(slug.current)]{ "slug": slug.current }
export type AllArticleSlugsQueryResult = Array<{
  slug: string
}>
// Variable: pillarsQuery
// Query: *[_type == "pillar"] | order(order asc){    _id, title, "slug": slug.current, summary, order  }
export type PillarsQueryResult = Array<{
  _id: string
  title: string
  slug: string
  summary: string | null
  order: number
}>
// Variable: feeScheduleBySlugQuery
// Query: *[_type == "feeSchedule" && slug.current == $slug][0]{    _id,    dealerName,    "slug": slug.current,    setupFeeUsd,    annualAdminFeeUsd,    storageModel,    storageFlatFeeUsd,    storageScalingPercent,    typicalPurchaseSpreadPercent,    typicalLiquidationSpreadPercent,    minimumInvestmentUsd,    mandatorySalesCall,    sourceUrl,    dataVerifiedAt  }
export type FeeScheduleBySlugQueryResult = {
  _id: string
  dealerName: string
  slug: string
  setupFeeUsd: number | null
  annualAdminFeeUsd: number | null
  storageModel: 'flat' | 'scaling'
  storageFlatFeeUsd: number | null
  storageScalingPercent: number | null
  typicalPurchaseSpreadPercent: number
  typicalLiquidationSpreadPercent: number
  minimumInvestmentUsd: number | null
  mandatorySalesCall: boolean | null
  sourceUrl: string | null
  dataVerifiedAt: string
} | null
// Variable: allFeeSchedulesQuery
// Query: *[_type == "feeSchedule"] | order(dealerName asc){    _id, dealerName, "slug": slug.current, storageModel, typicalPurchaseSpreadPercent  }
export type AllFeeSchedulesQueryResult = Array<{
  _id: string
  dealerName: string
  slug: string
  storageModel: 'flat' | 'scaling'
  typicalPurchaseSpreadPercent: number
}>
// Variable: articlesByPillarQuery
// Query: *[_type == "article" && pillar->slug.current == $pillar] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    summary,    publishedAt,    updatedAt,    "pillar": pillar->{ "slug": slug.current }  }
export type ArticlesByPillarQueryResult = Array<{
  _id: string
  title: string
  slug: string
  summary: string | null
  publishedAt: string
  updatedAt: string
  pillar: {
    slug: string
  }
}>
// Variable: articleSlugsByPillarQuery
// Query: *[_type == "article" && pillar->slug.current == $pillar && defined(slug.current)]{ "slug": slug.current }
export type ArticleSlugsByPillarQueryResult = Array<{
  slug: string
}>
// Variable: authorBySlugQuery
// Query: *[_type == "author" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    jobTitle,    bio,    "portrait": portrait.asset->url,    "credentials": credentials[]->{ _id, name, credentialCategory, recognizedBy, dateEarned, verificationUrl },    "socialProfiles": socialProfiles[]{ platform, url }  }
export type AuthorBySlugQueryResult = {
  _id: string
  name: string
  slug: string
  jobTitle: string | null
  bio: string | null
  portrait: string | null
  credentials: Array<{
    _id: string
    name: string
    credentialCategory: 'certification' | 'degree' | 'license'
    recognizedBy: string | null
    dateEarned: string | null
    verificationUrl: string | null
  }> | null
  socialProfiles: Array<{
    platform:
      | 'finra-brokercheck'
      | 'linkedin'
      | 'other'
      | 'sec-iapd'
      | 'twitter'
    url: string
  }> | null
} | null
// Variable: allAuthorsQuery
// Query: *[_type == "author"] | order(name asc){    _id, name, "slug": slug.current, jobTitle, "portrait": portrait.asset->url  }
export type AllAuthorsQueryResult = Array<{
  _id: string
  name: string
  slug: string
  jobTitle: string | null
  portrait: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "article" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedAt,\n    updatedAt,\n    "pillar": pillar->{ _id, title, "slug": slug.current, order },\n    "author": author->{ \n  _id,\n  name,\n  "slug": slug.current,\n  jobTitle,\n  bio,\n  "portrait": portrait.asset->url,\n  "credentials": credentials[]->{ _id, name, credentialCategory, recognizedBy, dateEarned, verificationUrl },\n  "socialProfiles": socialProfiles[]{ platform, url }\n },\n    "reviewedBy": reviewedBy{\n      reviewedAt,\n      "reviewer": reviewer->{ \n  _id,\n  name,\n  "slug": slug.current,\n  jobTitle,\n  bio,\n  "portrait": portrait.asset->url,\n  "credentials": credentials[]->{ _id, name, credentialCategory, recognizedBy, dateEarned, verificationUrl },\n  "socialProfiles": socialProfiles[]{ platform, url }\n }\n    },\n    body,\n    seo\n  }\n': ArticleBySlugQueryResult
    '\n  *[_type == "article" && defined(slug.current)]{ "slug": slug.current }\n': AllArticleSlugsQueryResult
    '\n  *[_type == "pillar"] | order(order asc){\n    _id, title, "slug": slug.current, summary, order\n  }\n': PillarsQueryResult
    '\n  *[_type == "feeSchedule" && slug.current == $slug][0]{\n    _id,\n    dealerName,\n    "slug": slug.current,\n    setupFeeUsd,\n    annualAdminFeeUsd,\n    storageModel,\n    storageFlatFeeUsd,\n    storageScalingPercent,\n    typicalPurchaseSpreadPercent,\n    typicalLiquidationSpreadPercent,\n    minimumInvestmentUsd,\n    mandatorySalesCall,\n    sourceUrl,\n    dataVerifiedAt\n  }\n': FeeScheduleBySlugQueryResult
    '\n  *[_type == "feeSchedule"] | order(dealerName asc){\n    _id, dealerName, "slug": slug.current, storageModel, typicalPurchaseSpreadPercent\n  }\n': AllFeeSchedulesQueryResult
    '\n  *[_type == "article" && pillar->slug.current == $pillar] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedAt,\n    updatedAt,\n    "pillar": pillar->{ "slug": slug.current }\n  }\n': ArticlesByPillarQueryResult
    '\n  *[_type == "article" && pillar->slug.current == $pillar && defined(slug.current)]{ "slug": slug.current }\n': ArticleSlugsByPillarQueryResult
    '\n  *[_type == "author" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    jobTitle,\n    bio,\n    "portrait": portrait.asset->url,\n    "credentials": credentials[]->{ _id, name, credentialCategory, recognizedBy, dateEarned, verificationUrl },\n    "socialProfiles": socialProfiles[]{ platform, url }\n  }\n': AuthorBySlugQueryResult
    '\n  *[_type == "author"] | order(name asc){\n    _id, name, "slug": slug.current, jobTitle, "portrait": portrait.asset->url\n  }\n': AllAuthorsQueryResult
  }
}
