import { createHash } from 'node:crypto'
import { globSync, readFileSync, writeFileSync } from 'node:fs'

// After `next build`, Next writes HTML for statically generated routes under
// `.next/server/app/`. We extract every inline <style> block, hash its content
// with SHA-256, and emit a TS file consumed by middleware.ts.
const files = globSync('.next/server/app/**/*.html')
const hashes = new Set<string>()
const styleRegex = /<style[^>]*>([\s\S]*?)<\/style>/gi

for (const file of files) {
  const html = readFileSync(file, 'utf8')
  for (const match of html.matchAll(styleRegex)) {
    const body = match[1] ?? ''
    const digest = createHash('sha256').update(body).digest('base64')
    hashes.add(`'sha256-${digest}'`)
  }
}

const sortedHashes = [...hashes].sort()

const body = `// Auto-generated by scripts/generate-style-hashes.ts
// Rebuild by running: pnpm generate:style-hashes
export const STYLE_SRC_HASHES: readonly string[] = ${JSON.stringify(
  sortedHashes,
  null,
  2,
)} as const
`
writeFileSync('src/design/style-hashes.generated.ts', body, 'utf8')
console.log(`Wrote ${hashes.size} style hash(es).`)
